### ISSUE TITLE
Links broken on quickstart guide https://docs.laminas.dev/laminas-mvc/quick-start/

### ISSUE THREAD

**Issue by flipkickmedia** [laminas/tutorials#29] opened 2020-08-16 17:04 UTC
Links are broken in the content on the quick start page for the LaminasSkeletonModule zip package and 
LaminasSkeletonModule tarball download links - git hub returns a 404

https://docs.laminas.dev/laminas-mvc/quick-start/

**Comment by froschdesign** [comment] 2020-08-16 17:07
Duplicate of https://github.com/laminas/laminas-mvc/issues/41

**Closed by froschdesign** 2020-08-16 17:07 UTC
